### ISSUE TITLE
New Group

### ISSUE THREAD

**Issue by master2go** [mykle1/MMM-EOL#4]
Hello,
Thanks a lot for this great module. Can you please put Hominidae and Primates in there. That would be very very nice.
Many thanks in advance
Inge

**Comment by mykle1** [comment]
I am so sorry that I didn't see your message until just now. Please forgive me. I went and added "Hominidae" and "Primates" just now so that you can use those in the module., If you have more requests then it's better that you contact me at themykle1@gmail.com.

**Comment by Plainbroke** [comment]
Is there a way to run them all?  "null" or nothing between " " perhaps.
